export const strings = {
  age: "Age",
  location: "Location",
  favoriteDisneyCharacter: "Favorite Disney Character",
  favoriteDisneyMovie: "Favorite Disney Movie",
  favoriteDisneyland: "Favorite Disneyland",
  next: "Next",
  firstName: "First Name",
  lastName: "Last Name",
  birthDate: "Birth Date",
  city: "City",
  state: "State",
  updateProfile: "Update Profile",
  lastUpdated: "Last Updated:",
  cancel: "Cancel",
  editProfile: "Edit Profile",
  featuredCharacters: "Featured Characters!",
  page: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
  noTitleAvailable: (title: string) => `No ${title} available.`,
  previous: "Previous",
  back: "Back",
  featuredFilms: "Featured Films",
  shortFilms: "Short Films",
  tvShows: "TV Shows",
  exploreMoreCharacterDetails: "Explore More Character Details",
  none: "None",
  search: "Search...",
  searchResults: "Search Results",
  viewProfile: "VIEW PROFILE",
  clearSearch: "Clear search",
  findCharacter: "Find a character...",
  noResults: "No results",
  footer: "For educational use only. All characters and content are the property of Disney. This test is for private use and development testing only and should not be distributed for public consumption",
}