import type { Metadata } from "next";
import { ReactNode } from "react";
import "./globals.css";
import { CharacterProvider } from "@/contexts/CharacterContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CharacterProvider>
          {children}
        </CharacterProvider>
      </body>
    </html>
  );
}
